Repository laminas/laminas-mail, pull requests merged in 2020-06, with the labels that each got.

#90 Use link to ZF tracker
  src/Protocol/Smtp.php
Labels: Bug, Documentation

#93 Fix AddressList toString method to quote semicolon
  src/Header/AbstractAddressList.php
  test/Storage/MessageTest.php
Labels: Bug

#92 Use ::class constants instead of strings to class names
  src/Header/HeaderLoader.php
  src/Headers.php
  src/Message.php
  src/Storage/AbstractStorage.php
  src/Storage/Folder/Mbox.php
  src/Storage/Maildir.php
  src/Storage/Mbox.php
  src/Transport/Factory.php
  test/AddressListTest.php
  test/AddressTest.php
  test/Header/AddressListHeaderTest.php
  test/Header/ContentTransferEncodingTest.php
  test/Header/ContentTypeTest.php
  test/Header/DateTest.php
  test/Header/GenericHeaderTest.php
  test/Header/GenericMultiHeaderTest.php
  test/Header/HeaderNameTest.php
  test/Header/HeaderValueTest.php
  test/Header/HeaderWrapTest.php
  test/Header/IdentificationFieldTest.php
  test/Header/MessageIdTest.php
  test/Header/MimeVersionTest.php
  test/Header/ReceivedTest.php
  test/Header/SenderTest.php
  test/Header/SubjectTest.php
  test/Header/ToTest.php
  test/HeadersTest.php
  test/MessageFactoryTest.php
  test/MessageTest.php
  test/Protocol/Smtp/Auth/Crammd5Test.php
  test/Protocol/SmtpTest.php
  test/Storage/ImapTest.php
  test/Storage/MaildirFolderTest.php
  test/Storage/MaildirTest.php
  test/Storage/MaildirWritableTest.php
  test/Storage/MboxFolderTest.php
  test/Storage/MboxInterfaceTest.php
  test/Storage/MboxTest.php
  test/Storage/MessageTest.php
  test/Storage/Pop3Test.php
  test/Transport/FactoryTest.php
  test/Transport/FileOptionsTest.php
  test/Transport/SmtpTest.php
Labels: Enhancement

#31 Properly encode content-disposition header
  CHANGELOG.md
  src/Header/ContentDisposition.php
  src/Header/HeaderLoader.php
  test/Header/ContentDispositionTest.php
Labels: Enhancement
