Repository laminas/laminas-mail, pull requests merged in 2021-03, with the labels that each got.

#126 [2.14]: QA: Add specific type hints for $params
  src/Storage/Imap.php
  src/Storage/Pop3.php
Labels: Enhancement

#145 Fix #25; Skip empty continuation lines
  src/Headers.php
  test/Storage/MessageTest.php
Labels: Bug

#141 [2.14]: Tests: Fix references to ZF issue tracker
  test/Header/HeaderWrapTest.php
  test/MessageTest.php
  test/Storage/MessageTest.php
Labels: Documentation

#140 [2.14]: Fix: Fold long lines during SMTP communication
  src/Protocol/Smtp.php
  test/Transport/SmtpTest.php
Labels: Bug
