Repository laminas/laminas-mail, pull requests merged in 2023-05, with the labels that each got.

#233 Update to PHPUnit 10
  .gitignore
  composer.json
  composer.lock
  phpunit.xml.dist
  psalm-baseline.xml
  src/Header/HeaderLocatorInterface.php
  src/Headers.php
  test/AddressTest.php
  test/Header/AddressListHeaderTest.php
  test/Header/ContentDispositionTest.php
  test/Header/ContentTransferEncodingTest.php
  test/Header/ContentTypeTest.php
  test/Header/DateTest.php
  test/Header/GenericHeaderTest.php
  test/Header/HeaderLocatorTest.php
  test/Header/HeaderNameTest.php
  test/Header/HeaderValueTest.php
  test/Header/IdentificationFieldTest.php
  test/Header/MessageIdTest.php
  test/Header/MimeVersionTest.php
  test/Header/ReceivedTest.php
  test/Header/SenderTest.php
  test/Header/SubjectTest.php
  test/Header/ToTest.php
  test/MessageFactoryTest.php
  test/MessageTest.php
  test/Protocol/ProtocolTraitTest.php
  test/Protocol/SmtpPluginManagerCompatibilityTest.php
  test/Storage/MessageTest.php
  test/Storage/ParamsNormalizerTest.php
  test/Transport/FactoryTest.php
  test/Transport/SendmailTest.php
  test/Transport/SmtpTest.php
Labels: Awaiting Author Updates, Awaiting Maintainer Response, Enhancement

#237 Adds error code to runtime exception and adds test for rejected recip…
  src/Protocol/AbstractProtocol.php
  test/Protocol/SmtpTest.php
  test/TestAsset/SmtpProtocolSpy.php
Labels: Enhancement

#242 Fix return-type for `Sendmail::prepareSubject` and the `Sendmail::prepareParameters`
  psalm-baseline.xml
  src/Transport/Sendmail.php
Labels: Bug
